fix(seo-componet):add more meta tag
OI-wiki/gatsby-oi-wiki pull request #453
Opened 2020-09-12 08:25 UTC by Amybiubiu

2020-09-12 09:23 UTC, Enter-tainer requested changes

2020-09-12 09:23 UTC, Enter-tainer commented on src/components/Seo.tsx
> +      {(article ? true : null) && <meta property="og:article:tags" content={seo.tags} /> }
```suggestion
      {(article ? true : null) && <meta property="og:article:tag" content={seo.tags} /> }
```

see https://ogp.me/#no_vertical

2020-09-12 09:23 UTC, Enter-tainer commented on src/components/Seo.tsx
> +      {(article ? true : null) && <meta property="og:type" content="article" />}
这个可以直接写成 article && <meta .... 吧？

2020-09-13 08:31 UTC, Amybiubiu commented on src/components/Seo.tsx
> +      {(article ? true : null) && <meta property="og:type" content="article" />}
是的 （这多余的代码

2020-09-13 08:45 UTC, Enter-tainer commented on src/components/Seo.tsx
> +      {seo.tags && seo.tags.map((tag) => <meta property="og:article:tag" content={tag} />)}
循环渲染的时候需要加 key。下面也要类似的问题

2020-09-14 05:53 UTC, Enter-tainer commented
图片要不就统一钦定成 https://cdn.jsdelivr.net/npm/oicdn@0.0.2/wordArt.webp 好了。可以在 https://www.opengraph.xyz/ 和 https://search.google.com/structured-data/testing-tool 处进行测试

2020-09-14 13:42 UTC, Amybiubiu commented
> 图片要不就统一钦定成 https://cdn.jsdelivr.net/npm/oicdn@0.0.2/wordArt.webp 好了。可以在 https://www.opengraph.xyz/ 和 https://search.google.com/structured-data/testing-tool 处进行测试
是所有页面都用这张图吗？

2020-09-14 13:42 UTC, Enter-tainer commented
> > 图片要不就统一钦定成 [cdn.jsdelivr.net/npm/oicdn@0.0.2/wordArt.webp](https://cdn.jsdelivr.net/npm/oicdn@0.0.2/wordArt.webp) 好了。可以在 [opengraph.xyz](https://www.opengraph.xyz/) 和 [search.google.com/structured-data/testing-tool](https://search.google.com/structured-data/testing-tool) 处进行测试
> 
> 是所有页面都用这张图吗？

嗯是这样的

2020-09-14 13:44 UTC, Amybiubiu commented
> > > 图片要不就统一钦定成 [cdn.jsdelivr.net/npm/oicdn@0.0.2/wordArt.webp](https://cdn.jsdelivr.net/npm/oicdn@0.0.2/wordArt.webp) 好了。可以在 [opengraph.xyz](https://www.opengraph.xyz/) 和 [search.google.com/structured-data/testing-tool](https://search.google.com/structured-data/testing-tool) 处进行测试
> > 
> > 
> > 是所有页面都用这张图吗？
> 
> 嗯是这样的

okk

2020-09-15 14:37 UTC, Amybiubiu commented on src/components/Seo.tsx
> +      {seo.tags && seo.tags.map((tag) => <meta property="og:article:tag" content={tag} />)}
喔 好

2020-09-16 11:29 UTC, Enter-tainer requested changes

2020-09-16 11:29 UTC, Enter-tainer commented on src/components/Seo.tsx
> +/* eslint-disable react/jsx-key */
🌚

2020-09-16 11:40 UTC, Amybiubiu commented on src/components/Seo.tsx
> +/* eslint-disable react/jsx-key */
我又忘记了加key233 这就，正好把测试出来的问题修一下

2020-09-18 14:20 UTC, Enter-tainer requested changes

2020-09-18 14:20 UTC, Enter-tainer commented on src/components/Seo.tsx
> +  const generateKey = (pre:number):string => {
key 需要保持一致性的...这样不行吧

2020-09-18 14:20 UTC, Enter-tainer commented on src/components/Seo.tsx
> +  const generateKey = (pre:number):string => {
https://reactjs.org/docs/lists-and-keys.html#keys

2020-09-20 03:32 UTC, CBW2007 commented on src/components/Seo.tsx
> +  const generateKey = (pre:number):string => {
（我认为）有两种方法：
1. 直接使用内容作为key，如：key={tag} key={author}
2. 不同地方的i加上不同的值，如：key={i} key={i+100}

2020-09-20 13:13 UTC, CBW2007 commented on src/components/Seo.tsx
> +    <Helmet title={seo.title}>
react helmet好像是不接受props的吧？另外这个title的意义是什么 :thinking: <https://github.com/OI-wiki/gatsby-oi-wiki/blob/master/src/components/Layout.js#L102>

2020-09-20 15:43 UTC, Amybiubiu commented on src/components/Seo.tsx
> +    <Helmet title={seo.title}>
我现在看到了那里标红了，应该是不支持的，传的这个title 是别的地方粘贴过来了，然后我看seo里的所需的title相关信息都有，所以可以把这个删了，我这就改

2020-09-20 16:23 UTC, Amybiubiu commented on src/components/Seo.tsx
> +    <Helmet title={seo.title}>
刚刚有去改了一下，发现之前标红是有一个@types/react-helmet的依赖丢失了，，然后那个title的作用就是增加一个
`<title>seo.title</title>`没传递这个参数就是`<title></title>`tag内空了。（在把layout的helmet去除的情况下

2020-09-21 15:12 UTC, Amybiubiu commented on src/components/Seo.tsx
> +  const generateKey = (pre:number):string => {
第二个，react官方不是说兄弟节点需要有stable id吗？https://reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings
如果直接用index或者`tags_${index}`可能会出bug，https://reactjs.org/docs/reconciliation.html#keys（ 虽然这里不会）所以我还是改成第一种方法

2020-09-21 15:21 UTC, Amybiubiu commented on src/components/Seo.tsx
>      return `${pre}_${id}`
```suggestion

```

2020-09-21 15:23 UTC, Amybiubiu commented on src/components/Seo.tsx
>    }
```suggestion
 
```

2020-09-21 15:27 UTC, Amybiubiu commented on src/components/Seo.tsx
> +  }
```suggestion

```

2020-09-21 16:04 UTC, Enter-tainer approved these changes

2020-09-21 16:09 UTC, merged