Support auto graphql query types, Add formatting tools
OI-wiki/gatsby-oi-wiki pull request #903
Opened 2021-07-09 13:57 UTC by SkyeYoung

* support auto generates graphql query types
* add formatting tools
* clear gatsby-config.js

2021-07-09 14:33 UTC, diauweb requested changes

2021-07-09 14:33 UTC, diauweb commented on .gitignore
> +/example/src/__generated__/
```suggestion
__generated__/
```

2021-07-09 14:33 UTC, diauweb commented on gatsby-theme-oi-wiki/gatsby-config.js
> +// 暂时就放这儿了，主要是提供网站写 options 时的一个配置参考
请暂时把这些功能去掉， 这里没法review了

2021-07-09 14:33 UTC, diauweb commented on gatsby-theme-oi-wiki/.eslintrc.js
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
```suggestion
/* eslint-disable @typescript-eslint/no-var-requires */
```

2021-07-09 15:06 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/gatsby-config.js
> +// 暂时就放这儿了，主要是提供网站写 options 时的一个配置参考
好了，现在站点配置啥的差不多都 rollback 到之前的样子了。

2021-07-11 04:23 UTC, Enter-tainer approved these changes
辛苦了

2021-07-11 04:25 UTC, diauweb requested changes

2021-07-11 04:25 UTC, diauweb commented on gatsby-theme-oi-wiki/gatsby-config.js
> +const IS_PROD = IS_PRODUCTION || process.env.RENDER === 'true'
`IS_PRODUCTION` 和 `IS_PROD` 命名上的区别是什么呢 而且`IS_PRODUCTION` 只用过一次吧

2021-07-11 04:25 UTC, diauweb commented on gatsby-theme-oi-wiki/gatsby-config.js
> +    // },
这里还有用吗

2021-07-11 04:25 UTC, diauweb commented on gatsby-theme-oi-wiki/package.json
> +    "gatsby-plugin-typegen": "^2.2.4",
这里还有用吗

2021-07-11 04:25 UTC, diauweb commented on gatsby-theme-oi-wiki/package.json
> +    "js-yaml": "^4.1.0",
同上

2021-07-11 04:25 UTC, diauweb commented on genSchema.js
> +const {
是不是应该整理一下import?

2021-07-11 04:31 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/package.json
> +    "js-yaml": "^4.1.0",
这个我待会儿移除掉

2021-07-11 04:32 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/package.json
> +    "gatsby-plugin-typegen": "^2.2.4",
这两个都是有用的。

2021-07-11 04:34 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/gatsby-config.js
> +    // },
@diauweb 有用的，是 ts 的配置，只是现在用了会爆炸。

2021-07-11 04:39 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/gatsby-config.js
> +const IS_PROD = IS_PRODUCTION || process.env.RENDER === 'true'
> `IS_PRODUCTION` 和 `IS_PROD` 命名上的区别是什么呢 而且`IS_PRODUCTION` 只用过一次吧

我合并一下吧，忘掉了。

2021-07-11 04:40 UTC, SkyeYoung commented on genSchema.js
> +const {
@diauweb 我刚刚整理了一下，应该没有多余的了

2021-07-11 05:10 UTC, diauweb approved these changes
另外 稍微再整理一下commit吧

2021-07-11 08:29 UTC, Enter-tainer commented
commit history 太乱啦, 我这里就 squash merge 了

2021-07-11 08:29 UTC, merged