refactor: add types to Layout & related files
OI-wiki/gatsby-oi-wiki pull request #912
Opened 2021-07-16 11:06 UTC by SkyeYoung

In addition to styles. And at the same time some useless code was removed.

2021-07-16 11:11 UTC, SkyeYoung commented
提交的基本都是和 Layout 组件相关的 type 修改，大部分如果不改的话会导致各种 Error，所以就全放在一个 commit 里面了。（尝试分开提交一下午，觉得还是放一起比较好。）

style 相关的修改准备放到升级完 mui 之后。

2021-07-16 14:37 UTC, diauweb requested changes

2021-07-16 14:37 UTC, diauweb commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> -let easteregg = false
?

2021-07-16 14:37 UTC, diauweb commented on gatsby-theme-oi-wiki/src/components/BackTop.tsx
> +import { OnClickHandler } from '../types/common'
另外 这种东西有什么必要加type吗

2021-07-16 15:04 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/package.json
> +  "main": "index.ts",
🌚 这个是 IDE 自动重构改的，没看到，我后面移除掉

2021-07-16 15:05 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/components/BackTop.tsx
> +import { OnClickHandler } from '../types/common'
它报 Error 了，就加了（

2021-07-16 15:14 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/components/BackTop.tsx
> +import { OnClickHandler } from '../types/common'
但是加 type 这个我倒不太了解，我去看看文档。

2021-07-16 15:15 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/types/common.ts
> +export type AnyFunc = (...args: any) => any
那我处理一下 AnyFunc 吧

2021-07-17 15:47 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/components/Link/index.tsx
> +  tooltip?: StrBool;
这部分是不是原来的旧代码用的是 字符串类型的 true false 呀，有没有可能重构正规的 boolean

2021-07-17 15:47 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/utils/common.ts
> +export const isNull: IsNullType = (val) => val === null
这些函数感觉没必要封起来，搜了一下，isStrTrue 一共只用了三次，直接写成 == 'true' 更直观一点

2021-07-17 15:47 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/utils/common.ts
> +export const noopNull: NoopNull = () => null
这个改个名字？ NoopFunction 啥的会不会好一点，现在的名字不太直观

2021-07-17 15:49 UTC, diauweb requested changes
另外请修一下actions给的警告（

2021-07-17 15:49 UTC, diauweb commented on gatsby-theme-oi-wiki/src/utils/common.ts
> +export { pick, omit, throttle, uniq }
为什么不在用到的地方import

2021-07-17 15:49 UTC, diauweb commented on gatsby-theme-oi-wiki/src/utils/common.ts
> +export const noopNull: NoopNull = () => null
这些有什么用？

2021-07-17 15:49 UTC, diauweb commented on gatsby-theme-oi-wiki/src/components/Title.tsx
> +  noEdit: StrBool,
这个类型是给谁看的 文档吗？

2021-07-17 15:49 UTC, diauweb commented on gatsby-theme-oi-wiki/src/utils/common.ts
> +export const noopNull: NoopNull = () => null
我觉得除了多 import 一个文件和看代码的时候多找一次引用之外没有别的用处了

2021-07-17 15:49 UTC, diauweb commented on gatsby-theme-oi-wiki/src/components/NavAndDrawer/index.tsx
> +      color: textColor as string,
怎么只有这里有`as string`

2021-07-17 15:49 UTC, diauweb commented on gatsby-theme-oi-wiki/src/components/Link/index.tsx
> +
JSDoc 怎么被拆成单行注释了

2021-07-17 15:49 UTC, diauweb commented on gatsby-theme-oi-wiki/src/components/Link/index.tsx
> +type NeedExtendGatsbyLinkProps = 'onClick' | 'state' | 'activeClassName' | 'activeStyle' | 'partiallyActive' | 'replace'
加不上合适的类型可以不加了

2021-07-17 15:49 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/components/Link/index.tsx
> +  tooltip?: StrBool;
IIRC，Layout.tsx 里面是因为技术原因，不得不用字符串形式的 true 和 false。但是这边应该没有这种问题吧？当然，如果能干掉所有的 StrBool 就更好了，这东西我不是很喜欢（

2021-07-17 15:51 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/utils/common.ts
> +export const noopNull: NoopNull = () => null
我也感觉这几个函数的用处不是很大，主要是这些功能本身都很简单，写起来也不是很复杂

2021-07-17 15:52 UTC, Enter-tainer commented
如果没记错的话，Layout.js 里面是因为奇怪的技术原因，不得不用字符串形式的 true 和 false。但是其他的组件应该没有这种问题吧？之前的代码里面，有一部分地方是直接把 Layout 的参数给传进去，导致其他的组件里面也不同程度地含有一些 StrBool。可以考虑重构一下，把其他组件里面的 StrBool 删掉。当然，如果能干掉所有的 StrBool 就更好了，这东西我不是很喜欢（

2021-07-17 16:11 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/utils/common.ts
> +export const noopNull: NoopNull = () => null
lodash 有个 noop 函数了，它返回的是 undefined，所以这里命名的是 noopNull

2021-07-17 16:20 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/components/Link/index.tsx
> +
这是写晕了（

2021-07-18 09:47 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/components/NavAndDrawer/index.tsx
> +      color: textColor as string,
因为只有它是 undefined 的（

2021-07-20 03:30 UTC, SkyeYoung commented
冲突已经修好了，应该没啥问题了。

2021-07-20 05:06 UTC, diauweb commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> -let easteregg = false
Mark as resolved 不是 Mark as read

2021-07-20 05:42 UTC, diauweb reviewed
请把 `//TODO` 都去掉一下，特别是关于添加功能的部分
另外 `index.js` 为什么又变成 `index.ts` 了

2021-07-20 10:18 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> -let easteregg = false
ping @SkyeYoung

2021-07-20 10:26 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> -let easteregg = false
@diauweb 因为原来的做法是用这个变量控制只显示一次，现在直接改用 useEffect 的第二个参数来控制，就不需要这么麻烦了。

2021-07-20 10:42 UTC, SkyeYoung commented
改完了，actions 的警告籍由修改好的 eslint config 也处理了大半，剩下的是之后的 TS 化工作了。

2021-07-20 10:45 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> -let easteregg = false
![image](https://user-images.githubusercontent.com/25521218/126311235-7a301707-e338-4fdd-812a-a5265825f64a.png)

看起来没有起到你想要的效果

2021-07-20 10:48 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> -let easteregg = false
🤔 但是 production build 里面看起来是正常的

2021-07-20 13:34 UTC, diauweb approved these changes

2021-07-20 13:34 UTC, diauweb commented on gatsby-theme-oi-wiki/src/components/Search/index.tsx
> +  .then((response) => response.json())
```suggestion
).then((response) => response.json())
```

2021-07-21 08:22 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> +import {SmartLink} from './Link'
```suggestion
import {Typography} from '@material-ui/core'

import {makeStyles} from '@material-ui/core/styles'
import {graphql, useStaticQuery} from 'gatsby'
import React, {useEffect} from 'react'
import {SmartLink} from './Link'
```

这个地方的大括号周围的空格不见了，revert 力度过大了

2021-07-21 09:12 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> +import {SmartLink} from './Link'
@Enter-tainer 是现在的 eslint 配置 fix 的（不是我改的，是默认的配置），之后再统一处理一下，改一些配置？还可以考虑是不是要用 prettier 之类的？

2021-07-21 09:21 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> +import {SmartLink} from './Link'
但是别的文件里面的大括号周围都是有空格的，是不是可以统一一下

2021-07-21 09:27 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> +import {SmartLink} from './Link'
@Enter-tainer 那请问需要我现在就给 eslint 加上添加空格的配置吗？

2021-07-21 09:46 UTC, Enter-tainer commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> +import {SmartLink} from './Link'
好的，可以加

2021-07-21 09:59 UTC, SkyeYoung commented on gatsby-theme-oi-wiki/src/components/Footer.tsx
> +import {SmartLink} from './Link'
@Enter-tainer 搞定啦

2021-07-21 09:59 UTC, Enter-tainer approved these changes

2021-07-21 17:01 UTC, merged